# Site Settings
title: "@davidlapsleyio"
future: true
search: false

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-FDNSMGTHBN"
email: davidlapsleyio@gmail.com
description: My personal blog site
url: https://blog.davidlapsley.io
baseurl: ""

# Theme Settings
theme: minimal-mistakes-jekyll
# remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "David Lapsley, Ph.D."
  avatar: "/assets/images/headshot.jpg"
  bio: "CTO at [Actualyze.ai](https://www.actualyze.ai) - Enterprise-grade AI infrastructure and robust, scalable distributed systems"
  location:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/davidlapsley"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:davidlapsleyio@gmail.com"

# Reading Files
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  # - jekyll-remote-theme  # disabled for local dev

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
      toc: true
      toc_label: "Contents"
      toc_icon: "list"
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Pagination
paginate: 5
paginate_path: /page:num/
